INSERT INTO food_items (name, description, price, image_url) VALUES
('Classic Cheeseburger', 'Juicy grilled beef patty layered with melted cheddar cheese, fresh lettuce, tomatoes, and our secret sauce - a timeless favorite!', 6.99, '../assets/images/burger1.jpg'),
('Spicy Buffalo Wings', 'Crispy chicken wings tossed in fiery buffalo sauce, served with cooling ranch - crave the heat!', 7.49, '../assets/images/wings1.jpg'),
('Garlic Parmesan Fries', 'Crispy golden fries coated in garlic butter and parmesan - addictive and unforgettable!', 4.25, '../assets/images/fries1.jpg'),
('BBQ Chicken Pizza', 'Stone-baked pizza topped with smoky BBQ chicken, red onions, and a three-cheese blend - flavor explosion in every bite!', 9.99, '../assets/images/pizza1.jpg'),
('Creamy Alfredo Pasta', 'Fettuccine pasta tossed in a rich, creamy alfredo sauce, topped with parmesan - comfort food perfected.', 8.50, '../assets/images/pasta1.jpg'),
('Sizzling Veggie Fajitas', 'A sizzling platter of bell peppers, onions, mushrooms and more - healthy and heavenly.', 7.95, '../assets/images/fajitas1.jpg'),
('Honey Glazed Salmon', 'Tender salmon fillet with a sweet honey glaze and a citrus twist - light, elegant, and fulfilling.', 11.49, '../assets/images/salmon1.jpg'),
('Tandoori Chicken Wrap', 'Spiced tandoori chicken rolled in soft naan with mint chutney and veggies - bold Indian fusion.', 6.75, '../assets/images/wrap1.jpg'),
('Choco Lava Cake', 'Molten chocolate cake with a gooey center - rich, warm, and irresistible.', 4.95, '../assets/images/lava1.jpg'),
('Blueberry Pancake Stack', 'Fluffy pancakes layered with fresh blueberries, whipped cream, and maple syrup - breakfast bliss.', 5.99, '../assets/images/pancakes1.jpg'),
('Sushi Combo Platter', 'A colorful assortment of fresh nigiri, maki, and sashimi - sushi dreams delivered.', 13.99, '../assets/images/sushi1.jpg'),
('Loaded Nachos Supreme', 'Crispy tortilla chips piled high with cheese, beans, jalapeños, sour cream, and guacamole - party on a plate!', 8.25, '../assets/images/nachos1.jpg'),
('Creamy Tomato Soup', 'Silky tomato soup with a touch of basil and cream - warm your soul.', 3.99, '../assets/images/soup1.jpg'),
('Thai Green Curry', 'Aromatic green curry with chicken and coconut milk - exotic and comforting.', 9.50, '../assets/images/thaicurry1.jpg'),
('Bacon Egg Breakfast Burrito', 'Scrambled eggs, crispy bacon, cheese and salsa wrapped to-go - power breakfast.', 5.50, '../assets/images/burrito1.jpg'),
('Grilled Cheese Deluxe', 'Classic grilled cheese sandwich with three cheeses on artisan bread - simple yet extraordinary.', 4.75, '../assets/images/grilledcheese1.jpg'),
('Avocado Toast Special', 'Creamy avocado on toasted sourdough, topped with cherry tomatoes and chili flakes - health meets taste.', 5.25, '../assets/images/toast1.jpg'),
('Butter Chicken & Rice', 'Tender chicken in buttery tomato gravy with fluffy basmati rice - North Indian classic.', 9.75, '../assets/images/butterchicken1.jpg'),
('Prawn Tacos', 'Crispy prawns wrapped in soft tortillas with lime slaw and chipotle mayo - taco time elevated.', 8.99, '../assets/images/tacos1.jpg'),
('Margherita Pizza', 'Fresh tomatoes, basil, and mozzarella on a thin crispy base - Italian simplicity done right.', 7.95, '../assets/images/pizza2.jpg'),
('Teriyaki Chicken Bowl', 'Sticky rice topped with sweet teriyaki chicken and sautéed veggies - Asian comfort.', 8.50, '../assets/images/bowl1.jpg'),
('Double Decker Burger', 'Two juicy patties, cheese, pickles, lettuce, and sauce - built to satisfy.', 7.95, '../assets/images/burger2.jpg'),
('Falafel Wrap', 'Crunchy falafels, hummus, and veggies in pita - plant-based goodness.', 6.25, '../assets/images/falafel1.jpg'),
('Strawberry Smoothie', 'Blended fresh strawberries, yogurt, and a splash of honey - cool and energizing.', 3.75, '../assets/images/smoothie1.jpg'),
('Caramel Frappe', 'Iced coffee blended with caramel and whipped cream - sip into sweetness.', 4.25, '../assets/images/frappe1.jpg'),
('Veggie Spring Rolls', 'Crispy rolls packed with spiced veggies and served with tangy dip - crunchy snack delight.', 4.00, '../assets/images/springroll1.jpg'),
('Crispy Chicken Sandwich', 'Crispy fried chicken breast, lettuce, and mayo on a soft bun - crave it daily.', 6.50, '../assets/images/chickensandwich1.jpg'),
('Beef Burrito Bowl', 'Rice, beans, spicy beef, cheese, salsa and guac in a loaded bowl - every bite a fiesta.', 8.95, '../assets/images/burritobowl1.jpg'),
('Pepperoni Pizza', 'Mozzarella and spicy pepperoni over classic tomato sauce - every slice satisfies.', 8.75, '../assets/images/pizza3.jpg'),
('Mixed Berry Parfait', 'Layers of berries, yogurt, and granola - sweet, creamy, and crunchy.', 4.25, '../assets/images/parfait1.jpg'),
('Grilled Paneer Tikka', 'Char-grilled paneer cubes marinated in spices - smoky vegetarian delight.', 7.50, '../assets/images/paneer1.jpg'),
('Korean Fried Chicken', 'Crispy double-fried chicken tossed in Korean chili glaze - sweet, spicy, and sticky.', 9.25, '../assets/images/koreanchicken1.jpg'),
('Mediterranean Couscous Salad', 'A refreshing mix of couscous, cucumbers, olives, and feta - flavor-packed and fresh.', 6.45, '../assets/images/couscous1.jpg'),
('Fish & Chips', 'Golden fried fish with crispy fries and tartar dip - a British classic.', 9.95, '../assets/images/fishchips1.jpg'),
('Cheesy Baked Ziti', 'Oven-baked pasta with layers of cheese and tangy tomato sauce - comfort in every bite.', 8.25, '../assets/images/ziti1.jpg'),
('Spaghetti Carbonara', 'Spaghetti in creamy egg sauce with crispy pancetta - rich Roman taste.', 8.95, '../assets/images/carbonara1.jpg'),
('Caesar Salad', 'Crisp romaine, croutons, parmesan, and Caesar dressing - classy and refreshing.', 5.75, '../assets/images/caesarsalad1.jpg'),
('Stuffed Crust Pizza', 'Cheese-stuffed crust with all your favorite toppings - pizza to the edge!', 10.49, '../assets/images/pizza4.jpg'),
('Tuna Melt Sandwich', 'Melted cheese over savory tuna salad on grilled bread - gooey and satisfying.', 6.95, '../assets/images/tunamelt1.jpg'),
('Apple Pie Delight', 'Flaky crust, warm apples, and cinnamon - classic dessert bliss.', 4.95, '../assets/images/applepie1.jpg'),
('Veggie Lasagna', 'Layered pasta with seasoned vegetables, creamy béchamel, and cheese - hearty and healthy.', 7.99, '../assets/images/lasagna1.jpg'),
('Mango Sticky Rice', 'Sweet mango paired with coconut sticky rice - a Thai dessert dream.', 5.50, '../assets/images/mangorice1.jpg'),
('Chicken Shawarma Plate', 'Sliced chicken with garlic sauce, pickles, and rice - Middle Eastern magic.', 8.75, '../assets/images/shawarma1.jpg'),
('Chocolate Milkshake', 'Thick and creamy chocolate shake topped with whipped cream - sip into nostalgia.', 3.99, '../assets/images/milkshake1.jpg'),
('Veg Hakka Noodles', 'Stir-fried noodles with crunchy vegetables and soy sauce - Indo-Chinese treat.', 6.49, '../assets/images/noodles1.jpg'),
('Pesto Pasta', 'Pasta tossed in fresh basil pesto sauce - green, creamy, and full of flavor.', 7.99, '../assets/images/pesto1.jpg'),
('Cheesy Burger', 'A delicious burger loaded with cheese and fresh veggies.', 5.49, '../assets/images/burger.jpg'),
('Creamy Pasta', 'Italian-style pasta served with rich creamy white sauce.', 8.75, '../assets/images/pasta.jpg'),
('Fresh Garden Salad', 'A healthy bowl of greens with cherry tomatoes and vinaigrette.', 3.99, '../assets/images/salad.jpg');

